In [1]:
# Imports for stack overflow questions classification
import numpy as np 
import pandas as pd


In [2]:
# Loading the dataset in pandas dataframe

df = pd.read_csv(r'/content/train-sample_October_9_2012_v2.csv',error_bad_lines=False, engine="python")
df

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
Skipping line 26042: unexpected end of data


PostId     PostCreationDate  OwnerUserId    OwnerCreationDate  \
0      10035653  04/05/2012 20:37:35      1159226  01/19/2012 18:46:16   
1       8922537  01/19/2012 07:38:27      1157921  01/19/2012 07:31:34   
2       5962216  05/11/2011 09:43:05       696219  04/07/2011 06:38:45   
3      10070625  04/09/2012 08:16:57       490895  10/29/2010 04:59:18   
4       8960935  01/22/2012 12:10:17      1017103  10/27/2011 18:26:24   
...         ...                  ...          ...                  ...   
26035   3420844  08/06/2010 03:30:48       150062  08/04/2009 00:07:17   
26036   6402263  06/19/2011 12:10:00       353098  05/28/2010 16:44:20   
26037  12687683  10/02/2012 09:23:30       298875  03/20/2010 16:01:12   
26038   1528374  10/06/2009 22:10:10       151292  08/05/2009 19:01:38   
26039   9505085  02/29/2012 19:04:54      1236345  02/27/2012 19:18:03   

       ReputationAtPostCreation  OwnerUndeletedAnswerCountAtPostTime  \
0                             1                                    0   
1                             1                                    0   
2                            40                                    2   
3                             1                                    1   
4                            28                                    0   
...                         ...                                  ...   
26035                       103                                    2   
26036                        50                                    6   
26037                       535                                    1   
26038                         1                                    0   
26039                        28                                    1   

                                                   Title  \
0      what is the best way to connect my application...   
1      upload a zip file and get xml file information...   
2                    UIButton Background Change on click   
3                               using the pt_regs struct   
4      Can I use LIMIT function in SQL line where it'...   
...                                                  ...   
26035                    PHP Scrapping methods and help?   
26036                          master degree R&D project   
26037  How can i use Table Driven methods with delega...   
26038  Conversion from string to enumerated and numer...   
26039                  Replace a line of Text file [C++]   

                                            BodyMarkdown            Tag1  \
0      I know this question can be answered by search...             c++   
1      i make a up-loader to `upload a zip file with ...             php   
2      Can anyone tell me how to change UIButton back...  iphone-sdk-4.0   
3      I've recently started getting into linux kerne...           linux   
4      Can I use LIMIT function in SQL line where it'...           mysql   
...                                                  ...             ...   
26035  I have a site http://www.coldwellbankerpbr.com...             php   
26036  so, I'm taking a master degree in Computer Sci...            java   
26037  Hi i have been exhausted too many if compariza...              c#   
26038  I have the following function that will conver...             c++   
26039  *Its me, again...*\r\n\r\nOk, i have some prob...             c++   

                  Tag2       Tag3          Tag4 Tag5       PostClosedDate  \
0                  NaN        NaN           NaN  NaN  04/05/2012 23:31:34   
1                  xml    cakephp           zip  NaN  01/19/2012 16:43:00   
2                  NaN        NaN           NaN  NaN                  NaN   
3               module     kernel           NaN  NaN                  NaN   
4                limit        NaN           NaN  NaN                  NaN   
...                ...        ...           ...  ...                  ...   
26035              NaN        NaN           NaN  NaN                  NaN   
26036

In [3]:
df.tail()

PostId     PostCreationDate  OwnerUserId    OwnerCreationDate  \
26035   3420844  08/06/2010 03:30:48       150062  08/04/2009 00:07:17   
26036   6402263  06/19/2011 12:10:00       353098  05/28/2010 16:44:20   
26037  12687683  10/02/2012 09:23:30       298875  03/20/2010 16:01:12   
26038   1528374  10/06/2009 22:10:10       151292  08/05/2009 19:01:38   
26039   9505085  02/29/2012 19:04:54      1236345  02/27/2012 19:18:03   

       ReputationAtPostCreation  OwnerUndeletedAnswerCountAtPostTime  \
26035                       103                                    2   
26036                        50                                    6   
26037                       535                                    1   
26038                         1                                    0   
26039                        28                                    1   

                                                   Title  \
26035                    PHP Scrapping methods and help?   
26036                          master degree R&D project   
26037  How can i use Table Driven methods with delega...   
26038  Conversion from string to enumerated and numer...   
26039                  Replace a line of Text file [C++]   

                                            BodyMarkdown  Tag1  \
26035  I have a site http://www.coldwellbankerpbr.com...   php   
26036  so, I'm taking a master degree in Computer Sci...  java   
26037  Hi i have been exhausted too many if compariza...    c#   
26038  I have the following function that will conver...   c++   
26039  *Its me, again...*\r\n\r\nOk, i have some prob...   c++   

                  Tag2       Tag3          Tag4 Tag5       PostClosedDate  \
26035              NaN        NaN           NaN  NaN                  NaN   
26036              c++          c            rd  NaN  06/19/2011 12:13:37   
26037  design-patterns  delegates  table-driven  NaN  10/02/2012 13:20:22   
26038              NaN        NaN           NaN  NaN                  NaN   
26039           stream   ifstream           NaN  NaN                  NaN   

          OpenStatus  
26035           open  
26036      off topic  
26037  too localized  
26038           open  
26039           open

In [4]:
# Checking the data imbalance for different classes

df['OpenStatus'].value_counts()

open                   13125
not a real question     5611
not constructive        3023
off topic               2932
too localized           1349
Name: OpenStatus, dtype: int64

In [5]:
# Get the number of samples in the df
length = len(df)
length

26040

In [6]:
# Extract only title, markdown, and the open status from the data for training process
df = df[['Title', 'BodyMarkdown', 'OpenStatus']]
df.shape
df

Title  \
0      what is the best way to connect my application...   
1      upload a zip file and get xml file information...   
2                    UIButton Background Change on click   
3                               using the pt_regs struct   
4      Can I use LIMIT function in SQL line where it'...   
...                                                  ...   
26035                    PHP Scrapping methods and help?   
26036                          master degree R&D project   
26037  How can i use Table Driven methods with delega...   
26038  Conversion from string to enumerated and numer...   
26039                  Replace a line of Text file [C++]   

                                            BodyMarkdown           OpenStatus  
0      I know this question can be answered by search...        too localized  
1      i make a up-loader to `upload a zip file with ...  not a real question  
2      Can anyone tell me how to change UIButton back...                 open  
3      I've recently started getting into linux kerne...                 open  
4      Can I use LIMIT function in SQL line where it'...                 open  
...                                                  ...                  ...  
26035  I have a site http://www.coldwellbankerpbr.com...                 open  
26036  so, I'm taking a master degree in Computer Sci...            off topic  
26037  Hi i have been exhausted too many if compariza...        too localized  
26038  I have the following function that will conver...                 open  
26039  *Its me, again...*\r\n\r\nOk, i have some prob...                 open  

[26040 rows x 3 columns]

In [7]:
# Convert the OpenStatus labels into numbers for supervised training

df['OpenStatus'] = df['OpenStatus'].map({'open': 0, 'not a real question': 1, 'off topic': 2, 'not constructive': 3, 'too localized': 4})
df

<ipython-input-7-84c72688cffa>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['OpenStatus'] = df['OpenStatus'].map({'open': 0, 'not a real question': 1, 'off topic': 2, 'not constructive': 3, 'too localized': 4})


Title  \
0      what is the best way to connect my application...   
1      upload a zip file and get xml file information...   
2                    UIButton Background Change on click   
3                               using the pt_regs struct   
4      Can I use LIMIT function in SQL line where it'...   
...                                                  ...   
26035                    PHP Scrapping methods and help?   
26036                          master degree R&D project   
26037  How can i use Table Driven methods with delega...   
26038  Conversion from string to enumerated and numer...   
26039                  Replace a line of Text file [C++]   

                                            BodyMarkdown  OpenStatus  
0      I know this question can be answered by search...           4  
1      i make a up-loader to `upload a zip file with ...           1  
2      Can anyone tell me how to change UIButton back...           0  
3      I've recently started getting into linux kerne...           0  
4      Can I use LIMIT function in SQL line where it'...           0  
...                                                  ...         ...  
26035  I have a site http://www.coldwellbankerpbr.com...           0  
26036  so, I'm taking a master degree in Computer Sci...           2  
26037  Hi i have been exhausted too many if compariza...           4  
26038  I have the following function that will conver...           0  
26039  *Its me, again...*\r\n\r\nOk, i have some prob...           0  

[26040 rows x 3 columns]

In [8]:
# Data preprocessing for model training
from sklearn.model_selection import StratifiedShuffleSplit

train_df = df['Title']+ ''+ df['BodyMarkdown']
train_df = train_df.dropna()
labels_df = df['OpenStatus'].dropna().astype('int')
# Applying the method
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=0)
# sss.get_n_splits(train_df, labels_df)
train_idx = []
test_idx = []
print(sss.split(train_df, labels_df))
for i, (train_index, test_index) in enumerate(sss.split(train_df, labels_df)):
  print(f"Fold {i}:")
  print(f"  Train: index={train_index}")
  train_idx.append(train_index)
  test_idx.append(test_index)
  print(f"  Test:  index={test_index}")

print(len(train_idx[0]))
print(len(test_idx[0]))



<generator object BaseShuffleSplit.split at 0x7f05bc0595f0>
Fold 0:
  Train: index=[11979   217 19335 ... 19374  8416 24185]
  Test:  index=[21004 22382 13592 ...  3462 20830 23870]
23436
2604


In [9]:
#Check the stratified folds for train
from collections import Counter

label_check_lst = []
for idx in train_idx[0]:
  label_check_lst.append(labels_df[idx])

Counter(label_check_lst)

Counter({0: 11812, 3: 2721, 1: 5050, 2: 2639, 4: 1214})

In [10]:
# Check the strarified folds for test
label_check_lst = []
for idx in test_idx[0]:
  label_check_lst.append(labels_df[idx])
  
Counter(label_check_lst)

Counter({0: 1313, 2: 293, 1: 561, 3: 302, 4: 135})

In [11]:
# Separate the folds of train and test 

X_train = [train_df[idx] for idx in train_idx[0]]
X_test = [train_df[idx] for idx in test_idx[0]]
Y_train = [labels_df[idx] for idx in train_idx[0]]
Y_test = [labels_df[idx] for idx in test_idx[0]]

print(len(X_train))
print(len(X_test))

print(len(Y_train))
print(len(Y_test))


23436
2604
23436
2604


In [12]:
# Text preprocessing
print(X_train[0])

How To return Name and Email from ASP.NET in JSON formati need to return the names and emails which are selected from a MS SQL 2008 table in a JSON format. here is what I've got so far :

    public class RaumHelper
    {
        internal static string[] Raum()
        {
            List<string> raumObject = new List<string>();

            using (SqlConnection con = new SqlConnection(@"Data Source=Localhost\SQLEXPRESS;Initial Catalog=BOOK-IT-V2;Integrated Security=true;"))
            using (SqlCommand cmd = new SqlCommand(@"SELECT NAME, EMAIL FROM RAUM", con))
            {
                con.Open();
                using (SqlDataReader rdr = cmd.ExecuteReader())
                {
                    while (rdr.Read())
                    {
                        if (rdr["NAME"] != DBNull.Value && rdr["EMAIL"] != DBNull.Value)
                        {
                            raumObject.Add(rdr["NAME"].ToString());
                            raumObject.Add(rdr["EMAIL"].ToStrin

In [13]:
# Installing nltk for text processing
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [14]:
# Data preprocessing
import re
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk import pos_tag

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger') 

def text_processing(text):
  """Function for performing basic text processing
  Args:
    text: Text from each stack overflow question"""
  #text = X_train[0].lower()
  # print(re.findall(r"[0-9]+", text))
  processed_text = re.sub('[\[{()}\]0-9+]'," ",text) # Handling the brackets and digits
  processed_text = processed_text.replace("  "," ") #  Handling extra whitespaces
  processed_text = re.sub('[\W\s]+'," ", processed_text).replace("  ", " ") # Handling punctuation
  # print(processed_text)

  # Stopwords
  stop_words = stopwords.words('english')

  #Tokenize
  words = word_tokenize(processed_text)
  # Filter the words in the tokens that are not stop words 
  filtered_words = [word for word in words if word not in stop_words]

  # Stemming
  porter = PorterStemmer()
  stemmed = [porter.stem(word) for word in filtered_words] # Stem the words that are not stop words
  #print(stemmed)

  # POS Tags for each token
  pos = pos_tag(filtered_words)
  # print(pos)

  # Convert the stemmed words into a string
  stemmed_string =' '.join(stemmed)
  return stemmed_string


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


In [15]:
for index in range(len(X_train)):
  X_train[index] = text_processing(X_train[index])

for index in range(len(X_test)):
  X_test[index] = text_processing(X_test[index])

In [22]:
# Find the largest sentence in the train and test list and pad the tfidf vectors 
#len(max(X_train, key=len))
import numpy as np
def find_max_list_idx(list):
    list_len = [len(i) for i in list]
    return np.argmax(np.array(list_len)) 

find_max_list_idx(X_train)

13689

In [26]:
X_train[13689]

'error consum soap web servicei tri consum web servic expos percuss cm order creat content item programmat when attempt add web refer visual studio howev visual studio alert follow the document understood could process the wsdl document contain link could resolv dtd prohibit xml document i experi work percuss cm i clue start resolv problem is visual studio set i might abl overrid make work i alreadi request assist percuss tech support monday i gotten use help inform back edit just case help resolv issu entir wsdl pre code lt xml version encod utf gt lt wsdl definit name content targetnamespac urn www percuss com content xmln com urn www percuss com common xmln con urn www percuss com content xmln flt urn www percuss com fault xmln ns urn www percuss com systemservic xmln ns urn www percuss com uiservic xmln ns urn www percuss com assemblyservic xmln ns urn www percuss com securityservic xmln soap http schema xmlsoap org wsdl soap xmln wsdl http schema xmlsoap org wsdl xmln xsd http www

In [28]:
# Let's covvert words to numbers using TF-IDF 
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features = 10000)  # it contains only 10k features (fixed!)

xtrain_tfidf = vectorizer.fit_transform(X_train).toarray()  # converting words to numbers for train data 
xtest_tfidf = vectorizer.transform(X_test).toarray()   


10000

In [29]:
# Naive Bayes 
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()

clf.fit(xtrain_tfidf, Y_train)

predicted_naive = clf.predict(xtest_tfidf)

In [31]:
# Metrics :) 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix 

print('Accuracy Score \n',accuracy_score(predicted_naive, Y_test))
print('Confusion Matrix \n', confusion_matrix(predicted_naive, Y_test))
print('Classification Report \n', classification_report(predicted_naive, Y_test))

Accuracy Score 
 0.315668202764977
Confusion Matrix 
 [[398  58  28  26  44]
 [213  74  20  24  22]
 [192 109 138  38  20]
 [366 267  98 201  38]
 [144  53   9  13  11]]
Classification Report 
               precision    recall  f1-score   support

           0       0.30      0.72      0.43       554
           1       0.13      0.21      0.16       353
           2       0.47      0.28      0.35       497
           3       0.67      0.21      0.32       970
           4       0.08      0.05      0.06       230

    accuracy                           0.32      2604
   macro avg       0.33      0.29      0.26      2604
weighted avg       0.43      0.32      0.30      2604



In [32]:
# Importing more models for classification
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [34]:

svc=SVC(kernel="linear", C=1)
svc.fit(xtrain_tfidf, Y_train)

SVC(C=1, kernel='linear')

In [35]:
# SVM prediction
svm_preds = svc.predict(xtest_tfidf)
# Metrics :) 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix 

print('Accuracy Score \n',accuracy_score(svm_preds, Y_test))
print('Confusion Matrix \n', confusion_matrix(svm_preds, Y_test))
print('Classification Report \n', classification_report(svm_preds, Y_test))

Accuracy Score 
 0.630184331797235
Confusion Matrix 
 [[1128  290   99   87   93]
 [ 114  218   34   28   31]
 [  34   22  132   24    6]
 [  36   31   28  163    5]
 [   1    0    0    0    0]]
Classification Report 
               precision    recall  f1-score   support

           0       0.86      0.66      0.75      1697
           1       0.39      0.51      0.44       425
           2       0.45      0.61      0.52       218
           3       0.54      0.62      0.58       263
           4       0.00      0.00      0.00         1

    accuracy                           0.63      2604
   macro avg       0.45      0.48      0.46      2604
weighted avg       0.72      0.63      0.66      2604

